week5/generic_views/generic_views/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from apps.school.views import Subjects, TeachersDetailView, TeachersListView
from apps.school.views import StudentsListView, StudentsDetailView
from apps.school.views import SubjectsDetailView

urlpatterns = patterns(
    '',
    url(r'^$', Subjects.as_view(), name='subjects'),
    url(r'^teachers/(?P<pk>[-_\w]+)/$',
        TeachersDetailView.as_view(),
        name='teacher-detail',
        ),
    url(r'^students/(?P<pk>[-_\w]+)/$',
        StudentsDetailView.as_view(),
        name='student-detail',
        ),
    url(r'^subjects/(?P<pk>[-_\w]+)/$',
        SubjectsDetailView.as_view(),
        name='subject-detail',
        ),
    url(r'^teachers/$', TeachersListView.as_view(), name='teacher-list'),
    url(r'^students/$', StudentsListView.as_view(), name='student-list'),
    url(r'^admin/', include(admin.site.urls)),
)

week5/generic_views/apps/school/models.py
from django.db import models
from datetime import datetime


class Student(models.Model):
    first_name = models.TextField(max_length=100)
    last_name = models.TextField(max_length=100)
    created_at = models.DateTimeField(datetime.now())


class Teacher(models.Model):
    first_name = models.TextField(max_length=100)
    last_name = models.TextField(max_length=100)
    created_at = models.DateTimeField(datetime.now())


class Subject(models.Model):
    title = models.TextField(max_length=100)
    teacher = models.ForeignKey(Teacher)
    student = models.ManyToManyField(Student)
    created_at = models.DateTimeField(datetime.now())

week5/generic_views/apps/school/views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from apps.school.models import Student, Teacher, Subject


class Subjects(TemplateView):
    template_name = 'school/index.html'

    def get_context_data(self, **kwargs):
        subjects = Subject.objects.all()
        return {'subjects': subjects}


class SubjectsDetailView(DetailView):
    model = Subject
    template_name = 'school/show.html'

    def get_context_data(self, **kwargs):
        context = super(SubjectsDetailView, self).get_context_data(**kwargs)
        return context


class TeachersDetailView(DetailView):
    model = Teacher
    template_name = 'school/show.html'

    def get_context_data(self, **kwargs):
        teacher = super(TeachersDetailView, self).get_context_data(**kwargs)
        courses = Subject.objects.filter(teacher=teacher['teacher'].id)
        context = {
            'teacher_info': teacher,
            'course_list': courses,
        }
        return context


class TeachersListView(ListView):
    model = Teacher
    template_name = 'school/index.html'

    def get_context_data(self, **kwargs):
        context = super(TeachersListView, self).get_context_data(**kwargs)
        return context


class StudentsDetailView(DetailView):
    model = Student
    template_name = 'school/show.html'

    def get_context_data(self, **kwargs):
        student = super(StudentsDetailView, self).get_context_data(**kwargs)
        courses = Subject.objects.filter(student=student['student'].id)
        context = {
            'student_info': student,
            'course_list': courses,
        }
        return context


class StudentsListView(ListView):
    model = Student
    template_name = 'school/index.html'

    def get_context_data(self, **kwargs):
        context = super(StudentsListView, self).get_context_data(**kwargs)
        return context

week5/generic_views/apps/school/templates/school/index.html
<!doctype html>
<html>
<head>
    <title>Class based views</title>
</head>
<body>
<h1>School</h1>
{% for subject in subjects %}
<p><a href="{% url 'subject-detail' subject.id %}">{{subject.title}}</a></p>
{% endfor %}

{% for teacher in teacher_list %}
<p><a href="{% url 'teacher-detail' teacher.id %}">{{teacher.first_name}} {{teacher.last_name}}</a></p>
{% endfor %}

{% for student in student_list %}
<p><a href="{% url 'student-detail' student.id %}">{{student.first_name}} {{student.last_name}}</a></p>
{% endfor %}

<p><a href="{% url 'teacher-list' %}">See all teachers</a> <a href="{% url 'student-list'%}">See all students</a> <a href="{% url 'subjects' %}">See all subjects</a></p>


</body>
</html>

week5/generic_views/apps/school/templates/school/show.html
<!doctype html>
<html>
<head>
    <title>Generic views</title>
</head>
<body>
{% if student_info %}
    <h1>Student</h1>
    <p>{{ student_info.student.first_name }} {{ student_info.student.last_name }}</p>
    {% if course_list %}
    <ul>
        {% for course in course_list %}
            <li><a href="{% url 'subject-detail' course.id %}">{{course.title}}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
{% endif %}

{% if teacher_info %}
    <h1>Teacher</h1>
    <p>{{ teacher_info.teacher.first_name }} {{ teacher_info.teacher.last_name }}</p>
    {% if course_list %}
    <ul>
        {% for course in course_list %}
            <li><a href="{% url 'subject-detail' course.id %}">{{course.title}}</a></li>
        {% endfor %}
    </ul>
    {% endif %}

{% endif %}


{% if subject %}
    <p>Course name: {{subject.title}}</p>
    <p>Teacher: <a href="{% url 'teacher-detail' subject.teacher.id %}">{{subject.teacher.first_name}} {{subject.teacher.last_name}}</a></p>
    <p>Students: </p>
    {% if subject.student %}
    <ul>
        {% for student in subject.student.all %}
        <li><a href="{% url 'student-detail' student.id %}">{{student.first_name}} {{student.last_name}}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
{% endif %}
</body>
</html>